# Generated by Django 5.2.5 on 2025-08-27 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del artista o banda', max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('foto_artista', models.ImageField(blank=True, null=True, upload_to='img_artistas/')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='app_artista.artista')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
            },
        ),
    ]
